
GET http://localhost:5000/person HTTP/1.1
Content-Type: application/json

### INSERT ENTITY A
POST http://localhost:5000/person/insert_entity HTTP/1.1
Content-Type: application/json

{
    "name"      : "Jose",
    "lastName"  : "Silvado",
    "cpf"       : "1234567899",
    "perfil"      : "Admin"
}

### INSERT ENTITY B
POST http://localhost:5000/person/insert_entity HTTP/1.1
Content-Type: application/json

{
    "name"      : "Carlos",
    "lastName"  : "Moises",
    "cpf"       : "54353903314",
    "perfil"      : "Admin"
}

###
GET http://localhost:5000/person/select_entity HTTP/1.1 
Content-Type: application/json

### SELECT ENTITY ONE
GET http://localhost:5000/person/select_entity_one/b0784a33-c5f8-43b1-89aa-d8ad524f3e44 HTTP/1.1 
Content-Type: application/json

### UPDATE
POST http://localhost:5000/person/update_entity HTTP/1.1
Content-Type: application/json

{
    "id"      : "b0784a33-c5f8-43b1-89aa-d8ad524f3e44",
    "name"    : "Morgado"
}